version: '3'

services:
  app-server:
    build: ./provisioning
    image: ebts
    environment:
        PHP_IDE_CONFIG: "serverName=ebts.local"
        XDEBUG_CONFIG: "remote_host=172.17.0.1"
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - ./provisioning/php.ini:/usr/local/etc/php/php.ini:cached
      - ./:/application:cached
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ebts
    volumes:
      - ./provisioning/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:cached
      - ./storage/tmp/db:/var/lib/mysql:cached
    networks:
      - app-network

  mysql-test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ebts-testing
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge