version: '3'

services:
  app-server:
    build: ./provisioning
    image: ebts
    extra_hosts:
      ebts.local: 172.17.0.1
    environment:
        PHP_IDE_CONFIG: "serverName=ebts.local"
        XDEBUG_CONFIG: "remote_host=172.17.0.1"
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - ./provisioning/php.ini:/usr/local/etc/php/php.ini:cached
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ebts
    volumes:
      - ./provisioning/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:cached
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ebts-testing

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app-server

